// <auto-generated />
using System;
using DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210408130400_UpdateRating")]
    partial class UpdateRating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BUS.Domains.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TypeProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeProductId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T-Shirtss",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Polos",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Texedo Shirts",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tank Tops",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dress Shirts",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kakis",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jeans",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Jogger",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Slim fit",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dress Pants",
                            TypeProductId = 2
                        });
                });

            modelBuilder.Entity("BUS.Domains.Fee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(2,2)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Fees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 0.05m,
                            Name = "Tax"
                        });
                });

            modelBuilder.Entity("BUS.Domains.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CustomerDistrict")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerProvince")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Fees")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Note")
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("Promotions")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BUS.Domains.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(2,2)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BUS.Domains.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Image")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Material")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Origin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("150");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductDescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("250");

                    b.Property<int?>("SaleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TypeProductId")
                        .HasColumnType("int");

                    b.Property<bool?>("isDel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TypeProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 121, DateTimeKind.Local).AddTicks(718),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 1",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3493),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 2",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3525),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 3",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3530),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 4",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3534),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 5",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3540),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 6",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3544),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 7",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3547),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 8",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3551),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 9",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3557),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 10",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3561),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 11",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3564),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 12",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3611),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 13",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3615),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 14",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3618),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 15",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3621),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 16",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3625),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 17",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3629),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 18",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3632),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 19",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3636),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 20",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3640),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 21",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3644),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 22",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3647),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 23",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3650),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 24",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3653),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 25",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3657),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 26",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3660),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 27",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3664),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 28",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3667),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 29",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 1
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3671),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 30",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3675),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 31",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3678),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 32",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3681),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 33",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3685),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 34",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3689),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 35",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3692),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 36",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3695),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 37",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3698),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 38",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3702),
                            Image = "product-1.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 39",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3706),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 40",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3709),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 41",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3765),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 42",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3769),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 43",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3773),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 44",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3776),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 45",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3779),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 46",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3782),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 47",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3785),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 48",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3788),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 49",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3792),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 50",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3796),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 51",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3799),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 52",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3802),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 53",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3805),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 54",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3808),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 55",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3812),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 56",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3815),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 57",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3818),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 58",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 4, 8, 6, 4, 0, 123, DateTimeKind.Local).AddTicks(3821),
                            Image = "product-2.png",
                            Material = "High quality water slide, with sun protection.",
                            Name = "Product 59",
                            Origin = "Viet nam",
                            Price = 98000.0,
                            ProductDescription = "Thiết kế, lên form chuẩn, tạo cảm giác thoải mái cho người mặc/Đường may tỉ mỉ/Thích hợp cho các bạn nam dạo phố, đi chơi, đi làm, tôn lên được sự trẻ trung, năng động",
                            TypeProductId = 2
                        });
                });

            modelBuilder.Entity("BUS.Domains.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("BUS.Domains.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CateIds")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(2,2)");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIds")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("TypeIds")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("isAll")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("BUS.Domains.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Feedback")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<byte>("Rate")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("BUS.Domains.TypeProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shirts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pants"
                        });
                });

            modelBuilder.Entity("BUS.Domains.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("BUS.Domains.Category", b =>
                {
                    b.HasOne("BUS.Domains.TypeProduct", null)
                        .WithMany("Categories")
                        .HasForeignKey("TypeProductId");
                });

            modelBuilder.Entity("BUS.Domains.OrderDetail", b =>
                {
                    b.HasOne("BUS.Domains.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BUS.Domains.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BUS.Domains.Product", b =>
                {
                    b.HasOne("BUS.Domains.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("BUS.Domains.TypeProduct", "Type")
                        .WithMany("Products")
                        .HasForeignKey("TypeProductId");

                    b.Navigation("Category");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BUS.Domains.ProductDetail", b =>
                {
                    b.HasOne("BUS.Domains.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BUS.Domains.Rating", b =>
                {
                    b.HasOne("BUS.Domains.Product", "Product")
                        .WithMany("Ratings")
                        .HasForeignKey("ProductId");

                    b.HasOne("BUS.Domains.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BUS.Domains.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BUS.Domains.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BUS.Domains.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BUS.Domains.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BUS.Domains.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BUS.Domains.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BUS.Domains.Product", b =>
                {
                    b.Navigation("ProductDetails");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("BUS.Domains.TypeProduct", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("BUS.Domains.User", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
